apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-eks-full-lab
  title: EduArn AWS EKS Full End-to-End Lab
  description: EduArn Backstage → Terraform → AWS → Kubernetes

spec:
  owner: group:platform-team
  type: service

  parameters:
    - title: Project Info
      required:
        - projectName
      properties:
        projectName:
          type: string
          title: Project Name

  steps:
    - id: fetch
      name: Generate Repo
      action: fetch:template
      input:
        url: ./skeleton
        values:
          project_name: ${{ parameters.projectName }}

    - id: publish
      name: Create GitHub Repo
      action: publish:github
      input:
        repoUrl: github.com?owner=rkpranjeet198&repo=${{ parameters.projectName }}-platform

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
