name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy to Kubernetes
        run: |
          aws eks update-kubeconfig --name ranjeet-eduarn-dev-cluster --region us-east-1
          kubectl apply -f k8s/
